CREATE TABLE todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    task TEXT NOT NULL,
    is_complete BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can view their own todos." 
    ON todos FOR SELECT 
    USING ((select auth.uid()) = user_id);

CREATE POLICY "Individuals can create todos." 
    ON todos FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Individuals can update their own todos." 
    ON todos FOR UPDATE 
    USING ((select auth.uid()) = user_id);

CREATE POLICY "Individuals can delete their own todos." 
    ON todos FOR DELETE 
    USING ((select auth.uid()) = user_id);